// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0gNj6HSsrIRDZgcS8eKE2issSgkWGz8Q',
    appId: '1:529545606854:web:ccbe38d001fcad5539c9c7',
    messagingSenderId: '529545606854',
    projectId: 'signlogin-7b9b8',
    authDomain: 'signlogin-7b9b8.firebaseapp.com',
    storageBucket: 'signlogin-7b9b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNI9bCjs1S_YxlSJrDMNTmi3Qzf3HddR4',
    appId: '1:529545606854:android:a8d8a5c084fd714839c9c7',
    messagingSenderId: '529545606854',
    projectId: 'signlogin-7b9b8',
    storageBucket: 'signlogin-7b9b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4FKDnqogfM9wSP8xlrc5fI3Z18EfnqE',
    appId: '1:529545606854:ios:92520fa098238a0f39c9c7',
    messagingSenderId: '529545606854',
    projectId: 'signlogin-7b9b8',
    storageBucket: 'signlogin-7b9b8.appspot.com',
    iosBundleId: 'com.example.signupLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4FKDnqogfM9wSP8xlrc5fI3Z18EfnqE',
    appId: '1:529545606854:ios:a51440c573d59e9339c9c7',
    messagingSenderId: '529545606854',
    projectId: 'signlogin-7b9b8',
    storageBucket: 'signlogin-7b9b8.appspot.com',
    iosBundleId: 'com.example.signupLogin.RunnerTests',
  );
}
